# Generated by Django 4.1.7 on 2023-03-03 19:16

import agenda_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agendalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tilte', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='agendaItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tilte', models.CharField(max_length=200, unique=True)),
                ('Discription', models.TextField(blank=True, null=True)),
                ('Createdate', models.DateTimeField(auto_now_add=True)),
                ('Duedate', models.DateTimeField(default=agenda_app.models.one_week_hence)),
                ('agenda_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_app.agendalist')),
            ],
            options={
                'ordering': ['Duedate'],
            },
        ),
    ]
